openapi: 3.0.1
info:
  title: AirlineReservation
  description: API Definition of AirlineReservation
  version: 1.0.0
servers:
- url: http://localhost:8290/reservation
paths:
  /:
    post:
      responses:
        default:
          description: Default response
